name: Deploy Infra

on: push

env:
  AWS_REGION: ap-southeast-2
  IAM_ROLE: arn:aws:iam::510769981514:role/np-iac-lab-github-actions-role

jobs:

  # Can add extra jobs/steps to run any pre deploy tasks

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get aws identity
        run: |
          aws sts get-caller-identity            

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3        

      - name: Terraform init
        run: terraform init

      - name: Terraform plan dev
        run: terraform plan -var-file dev.tfvars

      - name: Terraform apply dev
        run: terraform apply -var-file dev.tfvars --auto-approve              
